In [1]:
import pandas as pd
import numpy as np
import

In [3]:
data = np.loadtxt('test_data.txt',dtype=np.int32, delimiter=',')

In [4]:
data

array([[ 158,  295,  638],
       [ 295,  175,  594],
       [ 175,  158,  273],
       ...,
       [6004, 6008,    1],
       [6008, 6007,    1],
       [6006, 6002,    1]], dtype=int32)

In [5]:
data.shape

(5030, 3)

In [204]:
def process_one(data):
        data0 = set([data[i][0] for i in range(data.shape[0])])
        data1 = set([data[i][1] for i in range(data.shape[0])])
        #求交集
        lis = data0&data1
        #del_list = []
        dat = []
        for i in range(data.shape[0]):
            if (data[i][0] in lis)and(data[i][1] in lis):
                dat.append(data[i])
        #dat = np.delete(data,del_list,axis=0)
        
        return np.array(dat)

In [234]:
dat = process_one(data)
dat.shape

(2608, 3)

In [194]:
data0 = set([data[i][0] for i in range(data.shape[0])])
data1 = set([data[i][1] for i in range(data.shape[0])])

In [207]:
dat1 = list(data0&data1)

In [208]:
dat1

[18,
 23,
 24,
 26,
 27,
 56,
 58,
 61,
 64,
 65,
 67,
 83,
 91,
 94,
 107,
 114,
 121,
 126,
 127,
 128,
 139,
 140,
 144,
 145,
 149,
 150,
 158,
 159,
 164,
 175,
 176,
 179,
 185,
 188,
 192,
 194,
 197,
 198,
 205,
 208,
 214,
 222,
 223,
 227,
 231,
 234,
 237,
 242,
 255,
 259,
 268,
 271,
 272,
 292,
 293,
 295,
 296,
 299,
 300,
 303,
 325,
 338,
 346,
 360,
 368,
 375,
 377,
 382,
 383,
 395,
 401,
 409,
 413,
 434,
 437,
 440,
 444,
 447,
 455,
 456,
 460,
 476,
 485,
 493,
 500,
 501,
 505,
 513,
 517,
 521,
 523,
 526,
 528,
 542,
 543,
 545,
 546,
 551,
 557,
 558,
 564,
 567,
 569,
 572,
 575,
 582,
 587,
 588,
 589,
 590,
 593,
 594,
 608,
 614,
 621,
 628,
 643,
 652,
 663,
 671,
 675,
 682,
 683,
 685,
 697,
 699,
 708,
 716,
 726,
 732,
 734,
 738,
 745,
 748,
 755,
 757,
 777,
 783,
 789,
 799,
 806,
 808,
 809,
 811,
 816,
 822,
 826,
 827,
 828,
 831,
 833,
 835,
 846,
 847,
 856,
 862,
 872,
 874,
 877,
 879,
 880,
 881,
 883,
 887,
 891,
 898,
 900,
 903,
 912,


In [235]:
dic = {}
for item in dat:
            if dic.get(item[0])==None:
                dic[item[0]] = [item[1]]
            else:
                dic[item[0]].append(item[1])

In [247]:
len(dic)

2596

In [211]:
import copy

roads = []
roder = []
def findPath(v,path):
    print("path0:",path)
    lis = dic.get(v)
    if len(lis)>1:
        temp = copy.deepcopy(path)
        roder.append(temp)
     #   roads.append(copy.deepcopy(path))
    for i in lis:
        print(i)
        if i==path[0] or len(path)>7:
            roads.append(copy.deepcopy(path))
            continue
        
        path.append(i)
        findPath(i,path)
        
        '''
        if i!=path[0] and len(path)<=7:
            
            path.append(i)
            print("path:",path)
            findPath(i,path)
        elif i==path[0]:
            roads.append(copy.deepcopy(path))
            continue
        elif len(path)>7:
            path = roder[-1]
            roder.pop(-1)
            print(path)
            continue
      '''

In [212]:
findPath(145,[145])

path0: [145]
234
path0: [145, 234]
94
path0: [145, 234, 94]
145
91
path0: [145, 234, 94, 91]
223
path0: [145, 234, 94, 91, 223]
94
path0: [145, 234, 94, 91, 223, 94]
145
91
path0: [145, 234, 94, 91, 223, 94, 91]
223
path0: [145, 234, 94, 91, 223, 94, 91, 223]
94
237
237
505


In [213]:
roads

[[145, 234, 94],
 [145, 234, 94, 91, 223, 94],
 [145, 234, 94, 91, 223, 94, 91, 223],
 [145, 234, 94, 91, 223, 94, 91, 223],
 [145, 234, 94, 91, 223, 94, 91, 223],
 [145, 234, 94, 91, 223, 94, 91, 223]]

In [214]:
a = dic.get(94)

In [215]:
dic[237]

[114]

In [222]:
roads = []

In [237]:
recoder = []
def findp(v,path):

    lis = dic.get(v)
    if(lis==None):
        return
    for i in lis:
        temp = copy.copy(path)
        if i==path[0]:
            roads.append(temp)
            continue
        elif len(temp)>7:
            continue
        else:
            temp.append(i)
            findp(i,temp)
    return temp
            

In [238]:
findp(176,[176])

[176, 1039]

In [239]:
roads

[]

In [248]:
dic[6003]

[6007, 6004]

In [143]:
dic[4387]

[4940]

In [144]:
a = [1,2,3]
b = copy.copy(a)

In [145]:
b[1] = 0

In [291]:
dic[94]

[145, 91, 237]

In [170]:
a = dic.get(5000)

In [172]:
a = dic.keys()

In [175]:
if 5000 not in a:
    print(1)

1


In [251]:
b = dic.values()

In [253]:
b=[[7],[0,9],[8]]
len(b)

3

In [197]:
a = set([1,2,3,4,5,6])
b= set([2,3,4,5,7])
a&b

{2, 3, 4, 5}

In [255]:
d = [[1,2,3],[4,5,6],[7,8,9]]

In [267]:
with open("file",'w') as fw:
    for item in d:
        st = ""
        for j in item:
            st+=str(j)+','
        fw.write('%s\n'%st[:-1])
fw.close()

In [259]:
d[1]

[4, 5, 6]

In [262]:
",".join(str(d[1]))

'[,4,,, ,5,,, ,6,]'

In [263]:
str(d[1])

'[4, 5, 6]'

In [264]:
st = "1,2,3,"
st[:-1]

'1,2,3'

[[0.8,0.2]
 [0.2,0.8]] 

In [268]:
a = np.array([[0.8,0.2],[0.2,0.8]])

In [271]:
b = np.matmul(a,a)

In [272]:
np.matmul(b,a)

array([[0.608, 0.392],
       [0.392, 0.608]])

In [273]:
np.power(a,3)

array([[0.512, 0.008],
       [0.008, 0.512]])

In [276]:
b = np.array([[1],[2,3,6,7],[4,5,6],[2,3,4]])
sorted(b,key=lambda item:len(item))

[[1], [4, 5, 6], [2, 3, 4], [2, 3, 6, 7]]

In [277]:
sorted(b,key=lambda item:item[0])

[[1], [2, 3, 6, 7], [2, 3, 4], [4, 5, 6]]

In [289]:
#data1 = np.loadtxt("output.txt",dtype=np.int32,delimiter=',')
#data1 = np.loadtxt('output.txt',dtype=np.int32, delimiter=',')

data1 = np.array([[58,164,149],[164,149,58],[145,234,94],[145,234,94,91,223,94],[145,234,94,237,114,94],[145,234,505,413,485,234,94]])

In [290]:
data1

array([list([58, 164, 149]), list([164, 149, 58]), list([145, 234, 94]),
       list([145, 234, 94, 91, 223, 94]),
       list([145, 234, 94, 237, 114, 94]),
       list([145, 234, 505, 413, 485, 234, 94])], dtype=object)

In [292]:
three = []
six = []
seven = []
for item in data1:
    if len(item)==3:
        three.append(item)
    if len(item)==6:
        six.append(item)
    else:
        seven.append(item)

In [293]:
three

[[58, 164, 149], [164, 149, 58], [145, 234, 94]]

In [296]:
def func(three):
    d = []
    for item in three:
        s = sum(item)
        i=0
        num=0
        for j in item:
            num += j/s*np.power(10,i)
            i+=1
        d.append(num)
    return d

In [302]:
def func1(item):
    num=i=0
    s = sum(item)
    for j in item:
        num += j/s*np.power(10,i)
        i+=1
    return num

In [297]:
d = func(three)
    

In [304]:
three.append([23,34,45,4])

In [306]:
sorted(three,key=lambda item:func1(item),reverse=True)

[[23, 34, 45, 4], [58, 164, 149], [145, 234, 94], [164, 149, 58]]

In [ ]:
item = three

In [ ]:
lambda item:item[0]

In [305]:
three

[[58, 164, 149], [164, 149, 58], [145, 234, 94], [23, 34, 45, 4]]